using System.Text;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;

namespace Cs2Prak.Core.Binds;

public sealed record BindCommand(string label, string cmd, string desc);

public sealed record BindPlugin(string plugin, string id, IReadOnlyList<BindCommand> commands);

public static partial class BindsGenerator
{
    [GeneratedRegex(@"\s+")]
    private static partial Regex Whitespace();

    public static IReadOnlyList<BindPlugin> Catalog { get; } =
    [
        new BindPlugin("MatchZy", "matchzy",
        [
            new("Ready",            ".ready",       "Mark yourself ready"),
            new("Unready",          ".unready",     "Mark yourself not ready"),
            new("Pause",            ".pause",       "Pause the match"),
            new("Unpause",          ".unpause",     "Unpause the match"),
            new("Tactical timeout", ".tac",         "Call a tactical timeout"),
            new("Stay",             ".stay",        "Stay on side after knife round"),
            new("Switch",           ".switch",      "Switch sides after knife round"),
            new("Clear nades",      ".clear",       "Practice: remove all thrown grenades"),
            new("Rethrow",          ".rethrow",     "Practice: rethrow your last grenade"),
            new("Last nade",        ".last",        "Practice: teleport to last throw spot"),
            new("Back",             ".back",        "Practice: return to last saved position"),
            new("Spawn",            ".spawn",       "Practice: teleport to a spawn"),
            new("Best spawn",       ".bestspawn",   "Practice: teleport to the closest spawn"),
            new("Worst spawn",      ".worstspawn",  "Practice: teleport to the farthest spawn"),
            new("Add bot",          ".bot",         "Practice: place a crouching bot here"),
            new("Remove bots",      ".nobots",      "Practice: remove all placed bots"),
            new("Fast forward",     ".fastforward", "Practice: skip grenade flight time"),
            new("No flash",         ".noflash",     "Practice: toggle flash immunity"),
            new("Crosshair",        ".crosshair",   "Practice: drop a crosshair marker"),
            new("Break props",      ".break",       "Practice: toggle breakable props"),
        ]),

        new BindPlugin("WeaponPaints", "weaponpaints",
        [
            new("Skins menu",    "!ws",            "Open the weapon skins menu / refresh skins"),
            new("Knife menu",    "!knife",         "Open the knife menu"),
            new("Gloves menu",   "!gloves",        "Open the gloves menu"),
            new("Agents menu",   "!agents",        "Open the agents menu"),
            new("Music kit",     "!music",         "Open the music kit menu"),
            new("Reset weapons", "!resetweapons",  "Reset all applied weapon skins"),
        ]),

        new BindPlugin("PlayerSettings", "playersettings",
        [
            new("Settings menu", "!settings", "Open the player settings menu"),
        ]),
    ];

    public sealed record Generated(int Count, bool Written, string? Path, string Content);

    public static Generated Generate(JsonArray binds)
    {
        var lines = new StringBuilder();
        lines.Append("// sBinds.cfg — generated by cs2prak\n");
        lines.Append("// Plugin command binds.  Apply in CS2 console with:  exec sBinds\n");
        lines.Append('\n');

        var count = 0;
        foreach (var node in binds)
        {
            if (node is not JsonObject bind) continue;

            var key = Clean(bind["key"]);
            var command = Clean(bind["command"]);
            if (key.Length == 0 || command.Length == 0) continue;

            var action = command[0] is '!' or '.' ? "say " + command : command;

            action = action.Replace("\"", "");

            lines.Append($"bind \"{key}\" \"{action}\"\n");
            count++;
        }

        lines.Append("\necho \"[cs2prak] sBinds loaded\"\n");
        var content = lines.ToString();

        var cfgDir = SteamLocator.FindClientCfgDir();
        if (cfgDir is null) return new Generated(count, false, null, content);

        var path = Path.Combine(cfgDir, "sBinds.cfg");
        try
        {
            File.WriteAllText(path, CrLf(content), new UTF8Encoding(false));
            return new Generated(count, true, path, content);
        }
        catch (Exception e)
        {
            return new Generated(count, false, $"(write failed: {e.Message})", content);
        }
    }

    private static string CrLf(string text) => text.Replace("\n", "\r\n");

    private static string Clean(JsonNode? node)
    {
        var raw = node switch
        {
            JsonValue v when v.TryGetValue(out string? s) => s,
            null => "",
            _ => node.ToString(),
        };
        return Whitespace().Replace(raw ?? "", " ").Trim();
    }
}
